"""initial tables

Revision ID: d73efa892aac
Revises: 
Create Date: 2026-05-22 14:21:33.472766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd73efa892aac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('budget_group', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_summary',
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('snapshot_version', sa.String(), nullable=False),
    sa.Column('summary_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'snapshot_version', name='uq_monthly_summary_version')
    )
    op.create_table('category_rule',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_job',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_import_job_account_period', 'import_job', ['account_id', 'period'], unique=False)
    op.create_index('idx_import_job_status', 'import_job', ['status'], unique=False)
    op.create_table('import_item',
    sa.Column('import_job_id', sa.UUID(), nullable=False),
    sa.Column('pointer', sa.String(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_trade',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('source_import_job_id', sa.UUID(), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('confirmation_date', sa.Date(), nullable=True),
    sa.Column('trade_type', sa.String(), nullable=False),
    sa.Column('dividend_mode', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('shares', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('fund_code', sa.String(), nullable=True),
    sa.Column('fund_name', sa.String(), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('dedupe_key', sa.String(), nullable=False),
    sa.Column('source_pointer', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['source_import_job_id'], ['import_job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'dedupe_key', name='uq_investment_trade_dedupe')
    )
    op.create_index('idx_investment_trade_application_date', 'investment_trade', ['application_date'], unique=False)
    op.create_index('idx_investment_trade_confirmation_date', 'investment_trade', ['confirmation_date'], unique=False)
    op.create_table('transaction',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('source_import_job_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settlement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('counterparty', sa.String(), nullable=False),
    sa.Column('raw_description', sa.String(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('dedupe_key', sa.String(), nullable=False),
    sa.Column('source_pointer', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['source_import_job_id'], ['import_job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'dedupe_key', name='uq_transaction_dedupe')
    )
    op.create_index('idx_transaction_category_id', 'transaction', ['category_id'], unique=False)
    op.create_index('idx_transaction_occurred_at', 'transaction', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transaction_occurred_at', table_name='transaction')
    op.drop_index('idx_transaction_category_id', table_name='transaction')
    op.drop_table('transaction')
    op.drop_index('idx_investment_trade_confirmation_date', table_name='investment_trade')
    op.drop_index('idx_investment_trade_application_date', table_name='investment_trade')
    op.drop_table('investment_trade')
    op.drop_table('import_item')
    op.drop_index('idx_import_job_status', table_name='import_job')
    op.drop_index('idx_import_job_account_period', table_name='import_job')
    op.drop_table('import_job')
    op.drop_table('category_rule')
    op.drop_table('monthly_summary')
    op.drop_table('category')
    op.drop_table('audit_log')
    op.drop_table('account')
    # ### end Alembic commands ###
